# : Manager [[[

[manager]
cwd = { fg = "#f1dfda" }

# Tab
tab_active = { fg = "#561f0e", bg = "#ffb59e", bold = true }
tab_inactive = { fg = "#ffdbd0", bg = "#3a0b00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ebc44b", bg = "#ebc44b" }
marker_cut = { fg = "#f5e2a7", bg = "#f5e2a7" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d8c68d", bg = "#d8c68d" }

# Count
count_copied = { fg = "#231b00", bg = "#f5e2a7" }
count_cut = { fg = "#231b00", bg = "#f5e2a7" }
count_selected = { fg = "#561f0e", bg = "#d8c68d" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb59e" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#561f0e", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb59e", fg = "#561f0e", bold = true }
normal_alt  = { bg = "#53433f", fg = "#d8c2bc" }

# Select mode
select_main = { bg = "#e7bdb1", fg = "#442a22", bold = true }
select_alt  = { bg = "#53433f", fg = "#d8c2bc" }

# Unset mode
unset_main = { bg = "#d8c68d", fg = "#3a3005", bold = true }
unset_alt  = { bg = "#53433f", fg = "#d8c2bc" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb59e", bg = "#423734" }
progress_error = { fg = "#ffb4ab", bg = "#423734" }

# Permissions
permissions_t = { fg = "#c35a3c" }
permissions_w = { fg = "#988034" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#e5b51e" }
permissions_s = { fg = "#ff6637" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb59e" }
active = { fg = "#d8c68d", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb59e" }
value = { fg = "#f1dfda" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb59e", bg = "#561f0e" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb59e" }
title = {}
hovered = { fg = "#f5e2a7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423734" }
cand = { fg = "#ffb59e" }
rest = { fg = "#561f0e" }
desc = { fg = "#f1dfda" }
separator = " ▶ "
separator_style = { fg = "#f1dfda" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f1dfda" }
run = { fg = "#f1dfda" }
footer = { fg = "#442a22", bg = "#e7bdb1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d8c68d" }
title_warn = { fg = "#ffb59e" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f1dfda" },
    { name = "*/", fg = "#ffb59e" },
]

# : ]]]
