[config]

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.themes/Andromeda-standard-buttons/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.themes/Andromeda-standard-buttons/gtk-4.0/colors.css'

[templates.gtk3_theme]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4_theme]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.micro]
input_path = '~/.config/matugen/templates/micro-colors.micro'
output_path = '~/.config/micro/colorschemes/colors.micro'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.mpv]
input_path = '~/.config/matugen/templates/mpv-color.py'
output_path = '~/.config/mpv/color.py'

[templates.mpv-config]
input_path = '~/.config/matugen/templates/mpv-config-color.conf'
output_path = '~/.config/mpv/mpv.conf'
